//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePetShopManagementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTbl
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string mailId { get; set; }
        public decimal phone { get; set; }
        public string AnimalName { get; set; }
        public string serviceDesription { get; set; }
        public string address { get; set; }
    }
}
